version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/bundle"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/bundle/src/it/test"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/reactor"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/reactor/hello-world-maven-plugin"
    schedule:
      interval: "daily"
